// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
// (The root tsconfig sets `types: []` and only includes src/, so ESLint's
// default project for this file needs Node's types pulled in explicitly.)
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        // Unset during `prisma generate` in the Docker build, which never
        // connects; migrate/deploy fail loudly without it.
        url: process.env['DATABASE_URL'] as string,
    },
});
