// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import process from 'node:process';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        // Unset during `prisma generate` in the Docker build, which never
        // connects; migrate/deploy fail loudly without it.
        url: process.env['DATABASE_URL'] as string,
    },
});
